# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Sync with eclipse-score/module_template repository
on:
  workflow_call:
    inputs:
      pr_title:
        description: "Title for the template sync pull request"
        type: string
        default: "[Template Sync] Upstream template update"
      pr_commit_msg:
        description: "Commit message for the template sync"
        type: string
        default: "chore(template): upstream template update"
      template_sync_ignore_file_path:
        description: "Path to the template sync ignore file"
        type: string
        default: ".github/.templatesyncignore"

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false # 
      - name: Sync Template Changes
        uses: AndreasAugustin/actions-template-sync@v2.5.2
        with:
          source_gh_token: ${{ secrets.SCORE_APPROVALS_PAT}}
          target_gh_token: ${{ secrets.SCORE_APPROVALS_PAT}}
          source_repo_path: "eclipse-score/module_template"
          upstream_branch: "main"
          pr_title: ${{ inputs.pr_title }}
          pr_commit_msg: ${{ inputs.pr_commit_msg }}
          git_user_name: eclipse-score-bot
          git_user_email: 187756813+eclipse-score-bot@users.noreply.github.com
          template_sync_ignore_file_path: ${{ inputs.template_sync_ignore_file_path }}
